### ISSUE TITLE
StartTime and EndTime should be expressed as a UNIX timestamp

### ISSUE THREAD

**Issue by enolfc** [IFCA/caso#113]
### Description

`StarTime` and `EndTime` (potentially others) fields of the VM usage record should be expressed as UNIX timestamp, otherwise APEL rejects the records.

This is what's shown in the APEL logs:
```
2023-05-22 05:20:29,315 - loader - WARNING - Message rejected. Parsing unsuccessful: Unknown datetime format!: 2023-05-21 23:11:40
```

### Versions

This affects caso 4.x and newer

**Comment by alvarolopez** [comment]
@enolfc probably this is also true in `measure_time` (https://github.com/IFCA/caso/blob/master/caso/record.py#L167) and in `measure_time` and `start_time` in (https://github.com/IFCA/caso/blob/master/caso/record.py#L290). We are working separatedly here https://github.com/IFCA/caso/tree/fix/115

**Comment by enolfc** [comment]
> @enolfc probably this is also true in `measure_time` (https://github.com/IFCA/caso/blob/master/caso/record.py#L167) and in `measure_time` 

yes, according to this: https://docs.egi.eu/users/getting-started/architecture/#public-ip-usage-record

> and `start_time` in (https://github.com/IFCA/caso/blob/master/caso/record.py#L290).

The StAR contains this: 
```
The format of the record is XML, using QNames. The currently defined name space is http://euemi.eu/namespaces/2011/02/storagerecord, denoted as “sr” in this document. All time and duration formats are ISO types
```

So I expect this not to be converted
