### ISSUE TITLE
Block storage reported in GBytes instead of Bytes

### ISSUE THREAD

**Issue by thebe14** [IFCA/caso#116]
### Description

The [cASO storage accounting definition](https://docs.google.com/document/d/1Qmuw_g28gA8boPHy7_OiV_TlD5hO6XWhgJD1DMDjfQs/edit#heading=h.zqwe0ncymes) specifies that the fields _ResourceCapacityAllocated_ and _ResourceCapacityUsed_ are sent in bytes. cASO sends it in GBytes.

### Versions

4.1.1

**Comment by alvarolopez** [comment]
Hi @thebe14 can you confirm this is true? In https://github.com/IFCA/caso/blob/master/caso/messenger/ssm.py#L139 the capacity is translated into bytes.

**Comment by thebe14** [comment]
I missed that. But this is a bad practice. The record should be built in one place, not altered by the `_push_message_*` methods. Not to mention that that is not the only capacity field in a storage record. Will move this multiplication to the right place.

**Comment by alvarolopez** [comment]
@thebe14 yes, I agree with you.

We will fix this when we move to Pydantic 2, with full support for computed fields.
