### ISSUE TITLE
installation via pip doesn't work

### ISSUE THREAD

**Issue by marcoverl** [IFCA/caso#12]
Hello,
i've installed pyhton 2.7.9 in my SL6 system with RDO Havana installed,
then followed yout instructions in https://caso.readthedocs.org/en/latest/installation.html,
but got the errors below. Seems realated to some missing cffi stuff, however in my system the Package libffi-3.0.5-3.2.el6.x86_64 is already installed and latest version.

    [root@egi-cloud ~]# mkvirtualenv caso
    New python executable in caso/bin/python2.7
    Not overwriting existing python script caso/bin/python (you must use caso/bin/python2.7)
    Installing setuptools, pip...done.

    (caso)[root@egi-cloud ~]# pip install caso
    Collecting caso
      Using cached caso-0.1.1.tar.gz
        /root/.virtualenvs/caso/lib/python2.7/site-packages/pkg_resources/__init__.py:2462: PEP440Warning: 'pbr (0.5.2.5.g5b3e942)' is being parsed as a legacy, non PEP 440, version. You may find odd behavior and sort order. In particular it will be sorted as less than 0.0. It is recommend to migrate to PEP 440 compatible versions.
          PEP440Warning,
        Installed /tmp/pip-build-AOJivr/caso/.eggs/pbr-0.10.7-py2.7.egg
    [...]
    Installing collected packages: cffi, jsonpatch, jsonschema, cryptography, pytz, warlock, pyOpenSSL, oslo.serialization, simplejson, PrettyTable, requests, oslo.i18n, Babel, iso8601, netifaces, netaddr, stevedore, argparse, python-dateutil, dirq, python-ceilometerclient, python-glanceclient, python-keystoneclient, python-novaclient, six, oslo.utils, oslo.config, pbr, caso
      Running setup.py install for cffi
        building '_cffi_backend' extension    gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DUSE__THREAD -I/usr/local/lib/libffi-3.1/include -I/usr/local/include/python2.7 -c c/_cffi_backend.c -o build/temp.linux-x86_64-2.7/c/_cffi_backend.o    c/_cffi_backend.c:13:17: error: ffi.h: No such file or directory
        In file included from c/_cffi_backend.c:43:
    c/malloc_closure.h:33: error: expected specifier-qualifier-list before âffi_closureâ    c/malloc_closure.h: In function âmore_coreâ:    c/malloc_closure.h:69: warning: division by zero    c/malloc_closure.h:96: error: âunion mmaped_blockâ has no member named ânextâ    c/malloc_closure.h: At top level:    c/malloc_closure.h:105: error: expected â)â before â*â token    c/malloc_closure.h:113: error: expected â=â, â,â, â;â, âasmâ or â__attribute__â before â*â token    c/_cffi_backend.c:209: error: expected specifier-qualifier-list before âffi_cifâ    c/_cffi_backend.c: In function âcdataowninggc_deallocâ:    c/_cffi_backend.c:1521: error: âffi_closureâ undeclared (first use in this function)    c/_cffi_backend.c:1521: error: (Each undeclared identifier is reported only once    c/_cffi_backend.c:1521: error: for each function it appears in.)    c/_cffi_backend.c:1521: error: âclosureâ undeclared (first use in this function)
        c/_cffi_backend.c:1521: error: expected expression before â)â token
        c/_cffi_backend.c:4581: error: âcif_description_tâ has no member named âcifâ
        c/_cffi_backend.c:4582: error: âinvoke_callbackâ undeclared (first use in this function)
        c/_cffi_backend.c:4582: error: âFFI_OKâ undeclared (first use in this function)

        c/_cffi_backend.c: In function âinit_cffi_backendâ:
        c/_cffi_backend.c:5511: error: âFFI_DEFAULT_ABIâ undeclared (first use in this function)
        error: command 'gcc' failed with exit status 1
    [...]  
        ----------------------------------------    Command "/root/.virtualenvs/caso/bin/python2.7 -c "import setuptools, tokenize;__file__='/tmp/pip-build-AOJivr/cffi/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-m4lSdm-record/install-record.txt --single-version-externally-managed --compile --install-headers /root/.virtualenvs/caso/include/site/python2.7" failed with error code 1 in /tmp/pip-build-AOJivr/cffi

**Comment by alvarolopez** [comment]
This is due to a dependency not satisfied for a caso's dependency. I guess that you have to install the "-devel" package for libffi.

**Comment by marcoverl** [comment]
i've installed libffi-devel now and re-executed pip install caso, but still obtained the same error

**Comment by alvarolopez** [comment]
This is a dependency coming from cryptography>=0.2.1->pyOpenSSL>=0.11->python-glanceclient->caso. The error that you obtain comes from the lack of the header files included in the devel package, so installing it should solve it.

What is the output of `pip install cffi` and `rpm -qa libffi-devel`. Did you try to clean up the venv and install it again?

**Comment by marcoverl** [comment]
I re-built everything:
 1095  cd Python-2.7.9
 1096  ./configure --prefix=/usr/local --enable-unicode=ucs4 --enable-shared LDFLAGS="-Wl,-rpath /usr/local/lib"
 1097  make && make altinstall
 1098  cd ..
 1099  python2.7 ez_setup.py
 1100  easy_install-2.7 pip
 1101  pip2.7 install virtualenv
 1102  pip2.7 install virtualenvwrapper
 1103  virtualenv my27project
 1104  source my27project/bin/activate
 1105  source /usr/local/bin/virtualenvwrapper.sh
 1106  mkvirtualenv caso
 1107  pip install caso
but got the same error.

here is the uotput requested:

(caso)[root@egi-cloud ~]# rpm -qa libffi-devel
libffi-devel-3.0.5-3.2.el6.x86_64

(caso)[root@egi-cloud ~]# pip install cffi
Collecting cffi
  Using cached cffi-0.8.6.tar.gz
Requirement already satisfied (use --upgrade to upgrade): pycparser in ./.virtua
lenvs/caso/lib/python2.7/site-packages (from cffi)
Installing collected packages: cffi
  Running setup.py install for cffi
    building '_cffi_backend' extension
    gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstr
ict-prototypes -fPIC -DUSE__THREAD -I/usr/local/lib/libffi-3.1/include -I/usr/lo
cal/include/python2.7 -c c/_cffi_backend.c -o build/temp.linux-x86_64-2.7/c/_cff
i_backend.o
    c/_cffi_backend.c:13:17: error: ffi.h: No such file or directory
    In file included from c/_cffi_backend.c:43:
    c/malloc_closure.h:33: error: expected specifier-qualifier-list before âffi_
closureâ
    c/malloc_closure.h: In function âmore_coreâ:
    c/malloc_closure.h:69: warning: division by zero
    c/malloc_closure.h:96: error: âunion mmaped_blockâ has no member named ânext
â
    c/malloc_closure.h: At top level:
    c/malloc_closure.h:105: error: expected â)â before â*â token
    c/malloc_closure.h:113: error: expected â=â, â,â, â;â, âasmâ or â__attribute
[...]
    error: command 'gcc' failed with exit status 1
    Complete output from command /root/.virtualenvs/caso/bin/python2.7 -c "impor
t setuptools, tokenize;__file__='/tmp/pip-build-1brqV7/cffi/setup.py';exec(compi
le(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __fil
e__, 'exec'))" install --record /tmp/pip-etwIF0-record/install-record.txt --sing
le-version-externally-managed --compile --install-headers /root/.virtualenvs/cas
o/include/site/python2.7:
    running install
    
    running build
    
    running build_py
    
    creating build
    
    creating build/lib.linux-x86_64-2.7
    
    creating build/lib.linux-x86_64-2.7/cffi
    
    copying cffi/lock.py -> build/lib.linux-x86_64-2.7/cffi
    
    copying cffi/verifier.py -> build/lib.linux-x86_64-2.7/cffi
    
    copying cffi/api.py -> build/lib.linux-x86_64-2.7/cffi
    
    copying cffi/backend_ctypes.py -> build/lib.linux-x86_64-2.7/cffi
    
    copying cffi/vengine_cpy.py -> build/lib.linux-x86_64-2.7/cffi
    
    copying cffi/cparser.py -> build/lib.linux-x86_64-2.7/cffi
    
    copying cffi/ffiplatform.py -> build/lib.linux-x86_64-2.7/cffi
    
    copying cffi/vengine_gen.py -> build/lib.linux-x86_64-2.7/cffi
    
    copying cffi/gc_weakref.py -> build/lib.linux-x86_64-2.7/cffi
    
    copying cffi/commontypes.py -> build/lib.linux-x86_64-2.7/cffi
    
    copying cffi/__init__.py -> build/lib.linux-x86_64-2.7/cffi
    
    copying cffi/model.py -> build/lib.linux-x86_64-2.7/cffi
    
    running build_ext
    
    building '_cffi_backend' extension
    
    creating build/temp.linux-x86_64-2.7
[...]
    
    gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstr
ict-prototypes -fPIC -DUSE__THREAD -I/usr/local/lib/libffi-3.1/include -I/usr/lo
cal/include/python2.7 -c c/_cffi_backend.c -o build/temp.linux-x86_64-2.7/c/_cff
i_backend.o
    
    c/_cffi_backend.c:13:17: error: ffi.h: No such file or directory
    
    In file included from c/_cffi_backend.c:43:
    
    c/malloc_closure.h:33: error: expected specifier-qualifier-list before âffi_
closureâ
    
    c/malloc_closure.h: In function âmore_coreâ:
    
    c/malloc_closure.h:69: warning: division by zero
    
    c/malloc_closure.h:96: error: âunion mmaped_blockâ has no member named ânext
â
    
    c/malloc_closure.h: At top level:
[...]
    c/_cffi_backend.c:5511: error: âFFI_DEFAULT_ABIâ undeclared (first use in th
is function)
    
    error: command 'gcc' failed with exit status 1
    
    ----------------------------------------
    Command "/root/.virtualenvs/caso/bin/python2.7 -c "import setuptools, tokeni
ze;__file__='/tmp/pip-build-1brqV7/cffi/setup.py';exec(compile(getattr(tokenize,
 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" insta
ll --record /tmp/pip-etwIF0-record/install-record.txt --single-version-externall
y-managed --compile --install-headers /root/.virtualenvs/caso/include/site/pytho
n2.7" failed with error code 1 in /tmp/pip-build-1brqV7/cffi

**Comment by marcoverl** [comment]
ahh sorry! 
after logging out and then ligin againt it worked!
Successfully installed Babel-1.3 PrettyTable-0.7.2 argparse-1.3.0 caso-0.1.1 cffi-0.8.6 cryptography-0.7.2 dirq-1.6.1 iso8601-0.1.10 jsonpatch-1.9 jsonschema-2.4.0 netaddr-0.7.13 netifaces-0.10.4 oslo.config-1.6.0 oslo.i18n-1.3.0 oslo.serialization-1.2.0 oslo.utils-1.2.1 pbr-0.10.7 pyOpenSSL-0.14 python-ceilometerclient-1.0.12 python-dateutil-2.4.0 python-glanceclient-0.15.0 python-keystoneclient-1.0.0 python-novaclient-2.20.0 pytz-2014.10 requests-2.5.1 simplejson-3.6.5 six-1.9.0 stevedore-1.2.0 warlock-1.1.0

thanks for your prompt support!

**Comment by alvarolopez** [comment]
You're welcome, I'll close the issue then.
