### ISSUE TITLE
CpuDuration not properly reported

### ISSUE THREAD

**Issue by marcoverl** [IFCA/caso#26]
CpuDuration in caso-extract is taken from "hours" value response of the os-simple-tenant-usage API that gives information between the start date and the end date that were set as parameters in the API call, and not the difference between the end date (or the current date if VM not yet terminated) and the start date of the VM as would be expected, for example, if i do extract data starting from a date e.g. 1 hour before the VM termination date, CpuDuration ("hours") gives 1 hours:
$ curl -H "X-Auth-Token: ${KK:1}" -X GET -G  http://192.168.115.10:8774/v2/fe33652c76e94dec820a3d8645c5752d/os-simple-tenant-usage/fe33652c76e94dec820a3d8645c5752d -d start=2015-02-20T11:44:55  | python -m json.tool | grep -7 cb4b0789-62f5-4012-b617-9a4d3926add9
                 "ended_at": "2015-02-20T12:44:55.000000",
                 "flavor": "small-1core2GB40GB",
                 "hours": 1.0,
                 "instance_id": "cb4b0789-62f5-4012-b617-9a4d3926add9",
                 "local_gb": 40,
                 "memory_mb": 2048,
                 "name": "vcycle-padova-1424402978",
                 "started_at": "2015-02-20T03:32:06.000000",
                 "state": "terminated",
                 "tenant_id": "fe33652c76e94dec820a3d8645c5752d",
                 "uptime": 33169,

while if the extract date is e.g.  before the start date of the VM, i get the full CpuDuration exactly equal to WallDuration:

$ curl -H "X-Auth-Token: ${KK:1}" -X GET -G  http://192.168.115.10:8774/v2/fe33652c76e94dec820a3d8645c5752d/os-simple-tenant-usage/fe33652c76e94dec820a3d8645c5752d -d start=2015-02-19T11:44:55  | python -m json.tool | grep -7 cb4b0789-62f5-4012-b617-9a4d3926add9
                 "ended_at": "2015-02-20T12:44:55.000000",
                 "flavor": "small-1core2GB40GB",
                 "hours": 9.2136111111111116,
                 "instance_id": "cb4b0789-62f5-4012-b617-9a4d3926add9",
                 "local_gb": 40,
                 "memory_mb": 2048,
                 "name": "vcycle-padova-1424402978",
                 "started_at": "2015-02-20T03:32:06.000000",
                 "state": "terminated",
                 "tenant_id": "fe33652c76e94dec820a3d8645c5752d",
                 "uptime": 33169,

**Comment by alvarolopez** [comment]
Hi Marco.

Could you give a try to the following branch and check if it fixes your issue?

https://github.com/alvarolopez/caso/tree/bug/fix_start_end

**Comment by marcoverl** [comment]
ok, now is always CpuDuration >= Wallduration. In those cases where CpuDuration > WallDuration the difference is always of 7 seconds. Any explanation for this?

**Comment by alvarolopez** [comment]
Hi @marcoverl 

It is a matter of rounding. Unfortunately, OpenStack reports the CPU usage in hours (as a float), so the conversion and rounding to seconds unfortunately introduces some error (those 7 seconds that you get). The wall time is calculated directly by subtracting the end and start dates, so they are always accurate.

I've updated again that branch (https://github.com/alvarolopez/caso/tree/bug/fix_start_end) so that in case of discrepancies, cput = wall. Could you please try again?

**Comment by marcoverl** [comment]
ok, i have little statistics since last try, only 5 new records, but now is always CpuDuration = WallDuration, will check better tomorrow with more statistics
