### ISSUE TITLE
Can't extract data if Keystone v3 is used

### ISSUE THREAD

**Issue by cgimeno** [IFCA/caso#39]
caso is not able to extract usage records if keystone v3 API is being used. https://github.com/IFCA/caso/pull/40 solves that, but be aware: this pull request drops v2 support in favour of v3.

**Comment by alvarolopez** [comment]
This is solved here: https://github.com/alvarolopez/caso/commit/594f1e86f5bd0196ed79495bdaa4190a70ddd6f1

The changes are not merged back yet :-(

**Comment by alvarolopez** [comment]
Duplicate of https://github.com/IFCA/caso/issues/32
