### ISSUE TITLE
tenant or project in voms.json

### ISSUE THREAD

**Issue by itvasile** [IFCA/caso#44]
Following the warning in `caso.log`: 

    /usr/lib/python2.7/site-packages/caso/extract/base.py:72: DeprecationWarning: Using deprecated 'tenant' mapping, please use 'projects' instead

I used `project` and `projects` instead of `tenant`, which broke the accounting. The result is no FQAN line in logs, and the tenant/VO reported in accounting is  `None`

**Comment by alvarolopez** [comment]
What OpenStack version are you using?

Can you show me your mapping file?

**Comment by itvasile** [comment]
OpenStack Newton
voms.json looks like this:
{
"fedcloud.egi.eu": {
"project": "fedcloud.egi.eu"
},
"ops": {
"project": "ops"
},
"dteam": {
"project": "dteam"
}
}

In this form, I do not have the warning but it does not recognize the VO FQAN.

**Comment by alvarolopez** [comment]
You have to use `projects` instead of `project` and add it as a list, even if it contains a single element, like this:

    {
        "fedcloud.egi.eu": {
            "projects": ["fedcloud.egi.eu"]
        },
        "ops": {
            "projects": ["ops"]
        },
        "dteam": {
            "projects": ["dteam"]
        }
    }

I will update the documentation to be more clear.

**Comment by alvarolopez** [comment]
This was fixed in #46
