### ISSUE TITLE
missing depency 

### ISSUE THREAD

**Issue by jopina** [IFCA/caso#67]
### Description
Missing dependency for Caso 1.4.0 (python2-oslo-concurrency.noarch)
[Description of the bug or feature]

### Steps to Reproduce

1. [First Step]
Install caso rpm 
2. [Second Step]

[root@infra02 centos]# /usr/bin/caso-extract
Traceback (most recent call last):
  File "/usr/bin/caso-extract", line 6, in <module>
    from caso.cmd.extract import main
  File "/usr/lib/python2.7/site-packages/caso/cmd/extract.py", line 23, in <module>
    import caso.manager
  File "/usr/lib/python2.7/site-packages/caso/manager.py", line 23, in <module>
    from oslo_concurrency import lockutils
ImportError: No module named oslo_concurrency

3. [and so on...]
yum install python2-oslo-concurrency.noarch

4. 
caso-extract --version  
1.4.0

### Expected behaviour:

[What you expected to happen]

### Actual behaviour

[What actually happened]

### Versions

1.4.0

You can get this information from executing `caso --version`.

**Comment by alvarolopez** [comment]
We will fix it in the next cASO release.

**Comment by alvarolopez** [comment]
Fixed in cASO 1.4.2
